[package]
name = "qprust"
version = "0.1.0"
authors = ["massivelivefun <matthewlancefuller@gmail.com>"]
edition = "2021"
readme = "README.md"
license = "MIT/Apache-2.0/BSD3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
